New
JastinXyz/whatscode.js pull request #9
Opened 2022-05-14 05:07 UTC by ThisMe124

2022-05-14 06:07 UTC, JastinXyz commented
isi tittle yg bener lah anjim, biar gw tau

2022-05-14 06:23 UTC, ThisMe124 commented
Dah

2022-05-14 07:38 UTC, JastinXyz requested changes
bakal lebih baik kalo ada kek `<bot>.setStatus` sendiri, ini gunainnya klo kek gini tuh gimana?
:us: it would be better if it could be `<bot>.setStatus`, if it's like now how do you use it?

2022-05-14 07:41 UTC, ThisMe124 commented
> bakal lebih baik kalo ada kek `<bot>.setStatus` sendiri, ini gunainnya klo kek gini tuh gimana? 🇺🇸 it would be better if it could be `<bot>.setStatus`, if it's like now how do you use it?

Serah aja sih, soalnya ini aku add function doang gunain nya d.client.setStatus("text") gituh

2022-05-19 01:02 UTC, JastinXyz commented
> > bakal lebih baik kalo ada kek `<bot>.setStatus` sendiri, ini gunainnya klo kek gini tuh gimana? us it would be better if it could be `<bot>.setStatus`, if it's like now how do you use it?
> 
> Serah aja sih, soalnya ini aku add function doang gunain nya d.client.setStatus("text") gituh

interesting

2022-05-19 01:03 UTC, JastinXyz commented
This will be added later after I resolve the conflict

2022-05-19 03:17 UTC, JastinXyz commented
Closing this because it's better to use a regular function in Commit https://github.com/JastinXyz/whatscode.js/commit/177ac839cce51b0060130521139f63f2796c57f3

Thanks for this great idea!

2022-05-19 03:17 UTC, closed without merging